- name: authorized_keys | Set up authorized_keys for root
  authorized_key:
    user: root
    key: "{{ item }}"
  with_file:
    - public_keys/jordan
    - public_keys/matthewk
    - public_keys/bill
    - public_keys/mnxsolutions
  tags: "ssh-keys"

- name: authorized_keys | Set up authorized_keys for deploy
  authorized_key:
    user: deployuser
    key: "{{ item }}"
  with_file:
    - public_keys/jordan
    - public_keys/matthewk
    - public_keys/bill
    - public_keys/mnxsolutions
  tags: "ssh-keys"

- name: authorized_keys | Remove outdated authorized_keys for root
  authorized_key:
    user: root
    key: "{{ item }}"
    state: absent
  with_file:
    - public_keys/alexis
    - public_keys/eric
    - public_keys/patrick
  tags: "ssh-keys"

- name: authorized_keys | Remove outdated authorized_keys for deploy
  authorized_key:
    user: deployuser
    key: "{{ item }}"
    state: absent
  with_file:
    - public_keys/alexis
    - public_keys/eric
    - public_keys/patrick
  tags: "ssh-keys"
