---
- name: install | Install UFW firewall
  apt: package=ufw state=present

- name: conf | Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify: restart ufw

- name: conf | Configure ufw settings
  ufw:
    rule: "{{ item.rule }}"
    name: "{{ item.name }}"
  with_items:
    - { rule: 'allow', name: 'OpenSSH' }
  notify: restart ufw

- name: ufw | allow loadbalancer on 80
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    port: 80
  with_items: "{{ load_balancer_ip }}"
  when: inventory_hostname in groups['web']

- name: ufw | Allow Redis server connections for app servers
  ufw:
    rule: allow
    from_ip: "{{ hostvars[item[0]]['ip'] }}"
    port: "{{ item[1] }}"
  with_nested:
    - "{{ groups['app'] }}"
    - [ "6379", "6380", "26379" ]
  tags: ufw_config
  when: inventory_hostname in groups['redis']

- name: ufw | Allow Postgres server connections from app servers
  ufw:
    rule: allow
    from_ip: "{{ item }}"
    port: 5432
  with_items: "{{ app_server_ips }}"
  tags: ufw_config
  when: inventory_hostname in groups['database']

- name: ufw | Allow Redis server connections for database [sop-db2] server
  ufw:
    rule: allow
    from_ip: "10.0.100.19"
    port: "{{ item }}"
  with_items:
    - [ "6379", "6380", "26379" ]
  tags: ufw_config
  when: inventory_hostname in groups['redis']

- name: ufw | Stage servers allow port 80 and 443
  ufw:
    rule: allow
    port: "{{ item }}"
  with_items:
    - 80
    - 443
  when: staging is defined and inventory_hostname in groups['web']

- name: ufw | allow incoming MNX monitoring
  ufw:
    rule: allow
    from_ip: "{{ item.ip }}"
    port: "{{ item.port }}"
  with_items:
    - { ip: "24.231.212.64/29", port: 22 }
    - { ip: "204.8.232.8", port: 22 }
    - { ip: "198.62.109.40", port: 5666 }
    - { ip: "75.126.18.114", port: 22 }
    - { ip: "75.126.1.120", port: 22 }
    - { ip: "75.126.1.121", port: 22 }
    - { ip: "75.126.1.122", port: 22 }
    - { ip: "75.126.1.123", port: 22 }
  tags: mnx_monitoring

- name: ufw | allow outgoing MNX monitoring
  ufw:
    rule: allow
    to_ip: "198.62.109.116"
    to_port: "8086"
    direction: "out"
  tags: mnx_monitoring

- name: Enable ufw
  ufw: state=enabled
