---
## Per ansible recommended setup, the vars file has non-prefixed passthroughs to the vault_* variables
## defined in vault files, allowing for easier tracing of the variables, since the vaults aren't plain text
## https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults
- hosts: all
  gather_facts: False
  tasks:
    - name: Import vaults
      tags: always
      include_vars:
        dir: vars/vaults
    #- name: Import vault passthrough vars
    #  tags: always
    #  include_vars: vars.yml

- hosts: all
  user: root
  gather_facts: True
  roles:
    - common
    - unattended_upgrades
    # Does GitClear use papertrail as well?
    #- papertrail

- hosts:
  - errbit
  debugger: on_failed
  user: deployuser
  gather_facts: true
  roles:
    - { role: certbot, tags: certbot, become: true }
    - { role: mongodb, tags: mongodb, become: true }
    - { role: webserver, tags: nginx, become: true }
    # OSS passenger gets installed via the webserver role
    #- { role: passenger, tags: passenger, become: true }
    - { role: errbit, tags: [ rvm ruby bash ] }
  vars:
    - user: deployuser
    - ruby_version: 2.7.6
    - ruby_gemset: errbit
    - ruby_bundler_version: 2.4.16
