---
## Per ansible recommended setup, the vars file has non-prefixed passthroughs to the vault_* variables
## defined in vault files, allowing for easier tracing of the variables, since the vaults aren't plain text
## https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#variables-and-vaults
- hosts: all
  gather_facts: False
  tasks:
    - name: Import vaults
      tags: always
      include_vars:
        dir: vars/vaults
    - name: Import vault passthrough vars
      tags: always
      include_vars: vars.yml

- hosts: all
  user: root
  gather_facts: True
  roles:
    - common
    - unattended_upgrades
    - papertrail

- hosts:
  - errbit
  user: deployuser
  gather_facts: true
  roles:
    - { role: certbot, tags: certbot, become: true }
    - { role: mongodb, tags: mongodb_server, become: true }
    - { role: webserver, tags: errbit_app_server, become: true }
    - { role: passenger, tags: errbit_app_server, become: true }
    - { role: errbit, tags: errbit }
  vars:
    - ruby_version: 3.0.3
    - ruby_gemset: errbit
